### ISSUE TITLE
HUMBLE SUGGESTION: prefer csv over xlsx

### ISSUE THREAD

**Issue by maxjacobson** [CarlosPlusPlus/ltc-ruby#2]
(since I saw you were making issues on a saturday night I will chime in with an unsolicited one :smile:)

I think it's cool you track this: https://github.com/CarlosPlusPlus/ltc-ruby/blob/master/Rails_Casts_Tracking.xlsx but until GitHub can render it inline, I have to click thru to download the file and open it in an app to creep on your railscast viewing. GitHub [does richly render CSV](https://help.github.com/articles/rendering-csv-and-tsv-data/) so I think that would be nicer for me. Probably you can keep editing the CSV file in excel, just without rich stuff like bold and colors or w/e. Feel free to close and ignore of course :)

**Comment by CarlosPlusPlus** [comment]
Hmm, just realized I wasn't *watching* my own repositories, which is why I haven't been getting notifications. I think you're spot on, @maxjacobson --- I'll get to this sometime later today.

Been learning a lot from the Rails Casts, and like to summarize what I've learned. Use to do it via column width in Excel, but that no longer justifies the need to use the tool. Appreciate you providing the link, give me a few to take care of the change. :smile:

**Comment by CarlosPlusPlus** [comment]
Done and done in commit 8cb3124d2608ccc871f3bd66d87340b742f06558.

Here's a current link to the new version of the file:
https://github.com/CarlosPlusPlus/ltc-ruby/blob/master/RailsCasts_Tracker.csv

You totally rock man, thanks! :+1:
